//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string apkPath {
            get {
                return ResourceManager.GetString("apkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string apkVersion {
            get {
                return ResourceManager.GetString("apkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string env {
            get {
                return ResourceManager.GetString("env", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Exectype {
            get {
                return ResourceManager.GetString("Exectype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IpaPath {
            get {
                return ResourceManager.GetString("IpaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IpaVersion {
            get {
                return ResourceManager.GetString("IpaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to env,LIVE PROD
        ///Exectype,Local
        ///GlobalPassword,Testing1
        ///Hybridusername,0828717422
        ///LegacyContractUsername,0828716322
        ///nxtlvlusername,0818461725
        ///otpbypassnum,0715135502
        ///prepaidusername,0715036667
        ///usedpin,952789378178
        ///newpin,811135107072
        ///linkedNumberUsername,0826105483
        ///LinkedNumber,0646114571
        ///forgetpassnum,0828705152
        ///nonmahbuybunnum,0828716485
        ///contbundleusername,0828717233.
        /// </summary>
        public static string LIVE_PROD {
            get {
                return ResourceManager.GetString("LIVE_PROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcometo,Welcome to
        ///MyVodacom,My Vodacom
        ///PleaseEnterNumberLabel,PleaseEnterNumberLabel
        ///Cellphonenumber,Cellphone number
        ///CellphoneNumberTextBox,Cellphone Number Text Box
        ///CellphoneNumberTextBoxSMS,CellphoneNumberTextBox
        ///ProceedButton,Proceed button
        ///ProceedButtonForgrt,ProceedButton
        ///PasswordTextBox,Password
        ///UserNameTextBox,User name
        ///Loginto,Log in to
        ///Username,Username
        ///android.widget.ImageView,android.widget.ImageView
        ///Password,Password
        ///LoginButton,Login
        ///Platform_DefaultRenderer,Platform_DefaultR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LIVE_PROD_OR {
            get {
                return ResourceManager.GetString("LIVE_PROD_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to env,LIVE PROD
        ///Exectype,Local
        ///GlobalPassword,Testing1
        ///Hybridusername,0828717422
        ///LegacyContractUsername,0828716322
        ///nxtlvlusername,0818461725
        ///otpbypassnum,0715135502
        ///prepaidusername,0715036667
        ///usedpin,952789378178
        ///newpin,811135107072
        ///linkedNumberUsername,0826105483
        ///LinkedNumber,0646114571
        ///forgetpassnum,0828705152
        ///nonmahbuybunnum,0828716485
        ///contbundleusername,0828717233.
        /// </summary>
        public static string PRODA_External {
            get {
                return ResourceManager.GetString("PRODA_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcometo,Welcome to
        ///MyVodacom,My Vodacom
        ///PleaseEnterNumberLabel,PleaseEnterNumberLabel
        ///Cellphonenumber,Cellphone number
        ///CellphoneNumberTextBox,Cellphone Number Text Box
        ///ProceedButton,Proceed button
        ///ProceedButtonForgrt,ProceedButton
        ///PasswordTextBox,Password
        ///UserNameTextBox,User name
        ///Loginto,Log in to
        ///Username,Username
        ///android.widget.ImageView,android.widget.ImageView
        ///Password,Password
        ///LoginButton,Login
        ///Platform_DefaultRenderer,Platform_DefaultRenderer
        ///MenuButtonIcon,MenuButtonIcon
        ///Menu,Menu        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PRODA_External_OR {
            get {
                return ResourceManager.GetString("PRODA_External_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contbundleusername,
        ///forgetpassnum,
        ///globpassword,
        ///Hybridnum,
        ///Hybridnumpass,
        ///linknum,
        ///nonmahbuybunnum,
        ///nxtlvlusername,
        ///otpbypassnum,
        ///prepaidbuybundusername,
        ///prepaidpass,
        ///prepaidusername,.
        /// </summary>
        public static string UAT_External {
            get {
                return ResourceManager.GetString("UAT_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UAT_OR {
            get {
                return ResourceManager.GetString("UAT_OR", resourceCulture);
            }
        }
    }
}
